### ISSUE TITLE
Forward full environment in spawns

### ISSUE THREAD

**Issue by Petter-Programs** [open-mpi/ompi#13274]
Please submit all the information below so that we can understand the working environment that is the context for your question.

* If you have a problem building or installing Open MPI, [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-building-or-installing-open-mpi).
* If you have a problem launching MPI or OpenSHMEM applications, [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-launching-mpi-or-openshmem-applications).
* If you have a problem running MPI or OpenSHMEM applications (i.e., after launching them), [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-running-mpi-or-openshmem-applications).

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

Version 5.0.7

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From tarball

### Please describe the system on which you are running

* Operating system/version: Red Hat Enterprise Server; Linux 5.14.x (EL9-based distribution)
* Computer hardware: Intel Sapphire Rapids 8480
* Network type: NDR200

-----------------------------

## Details of the problem

Hi,

I recently discovered the forward environment setting and wanted to play around with it. It works great when I just launch across multiple nodes, but I can't get it to work with MPI_Comm_spawn. Is there any way to do this, or are there any plans to implement support?

Below is a little tester program. In short, the OMPI_ prefix seems to work for spawns too, but not setting the PRTE_MCA_prte_fwd_environment.

```c
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
#include <stdbool.h>

int main(int argc, char * argv[]) {
    MPI_Init(&argc, &argv);

    MPI_Comm parent = MPI_COMM_NULL;
    MPI_Comm_get_parent(&parent);

    bool am_parent = parent == MPI_COMM_NULL;

    int rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    if(am_parent)
    {
        MPI_Info the_info;
        MPI_Info_create(&the_info);

        MPI_Info_set(the_info, "PMIX_MAPBY", "PPR:1:NODE");
        MPI_Info_set(the_info, "PMIX_ENVAR", "PRTE_MCA_prte_fwd_environment=1");

        MPI_Comm_spawn(argv[0], MPI_ARGV_NULL, 2, the_info, 0, MPI_COMM_WORLD, &parent, MPI_ERRCODES_IGNORE);

        MPI_Info_free(&the_info);
    }

    const char *vars[] = {"OMPI_HELLOTHERE", "DUMMY_VAR"};
    const int nvars = sizeof(vars) / sizeof(vars[0]);

    char processor[MPI_MAX_PROCESSOR_NAME];
    int len_ignore;

    MPI_Get_processor_name(processor, &len_ignore);

    for (int i = 0; i < nvars; i++) {
        char *value = getenv(vars[i]);
        if (value) {
            printf("Hi from rank %d on %s. Child? %s. Environment variable %s found with value: %s\n",
                   rank, processor, am_parent ? "F" : "T", vars[i], value);
        } else {
            printf("Hi from rank %d on %s. Child? %s. Environment variable %s NOT found.\n",
                   rank, processor, am_parent ? "F" : "T", vars[i]);
        }
    }

    MPI_Finalize();

    return 0;
}
```

I ran this (outside of Slurm) with:

```
export PRTE_MCA_prte_fwd_environment=1
export DUMMY_VAR=test
export OMPI_HELLOTHERE=test1

mpirun --host host1:10,host2:10 --map-by ppr:1:node -np 2 ./forward

```

And here's my output:

```
Hi from rank 0 on host1. Child? F. Environment variable OMPI_HELLOTHERE found with value: test1
Hi from rank 0 on host1. Child? F. Environment variable DUMMY_VAR found with value: test
Hi from rank 1 on host2. Child? F. Environment variable OMPI_HELLOTHERE found with value: test1
Hi from rank 1 on host2. Child? F. Environment variable DUMMY_VAR found with value: test
Hi from rank 0 on host1. Child? T. Environment variable OMPI_HELLOTHERE found with value: test1
Hi from rank 0 on host1. Child? T. Environment variable DUMMY_VAR found with value: test
Hi from rank 1 on host2. Child? T. Environment variable OMPI_HELLOTHERE found with value: test1
Hi from rank 1 on host2. Child? T. Environment variable DUMMY_VAR NOT found.
```

By the way, I also tried to pass fwd-environment as a runtime option to mpirun, but it did not seem to recognize it:

```
mpirun --runtime-options fwd-environment --host host1:10,host2:10 --map-by ppr:1:node -np 2 ./forward
--------------------------------------------------------------------------
The specified runtime options directive is not recognized:

  Directive: fwd-environment

Please check for a typo or ensure that the directive is a supported
one.
--------------------------------------------------------------------------
```

**Comment by rhc54** [comment]
You raise several issues, so let me try to address them:

> OMPI_ prefix seems to work for spawns too

Yes, we always forward any envar prefixed with "OMPI_" as these are known OMPI-owned values

> but not setting the PRTE_MCA_prte_fwd_environment

I will investigate, but I suspect the issue is one of inheritance. The directive is applied to the initial launch, but may not be applied to the subsequent child launch minus a directive to tell us to do so. 

> tried to pass fwd-environment as a runtime option to mpirun, but it did not seem to recognize it

Hmmm...looks to me like the new form of that cmd line option didn't get implemented - my bad. For now, you can do it with just `--fwd-environment` on the cmd line.

**Comment by rhc54** [comment]
I have implemented/resolved the various issues so the behavior is as you expected - and matches the documentation:

https://github.com/openpmix/openpmix/pull/3613
https://github.com/openpmix/prrte/pull/2207

I'll be bringing these over to the latest release branches (PMIx v6 and PRRTE v4) - not sure when these might make their way over to OMPI, but it might not be until the next major release.

**Comment by Petter-Programs** [comment]
Thanks for the clarification, I am closing this issue now as it is resolved.

**Comment by rhc54** [comment]
Solving the first issue requires that we have the first child not just forward its environment, but also inherit the "fwd" directive so the second child can inherit it. Not a big deal.

The second issue doesn't quite make sense. We set the envars - including `LD_LIBRARY_PATH` - prior to fork/exec'ing the child process. There is no way to set it earlier, and it is in advance of any linker resolution. So I have no idea what's going on there.

**Comment by rhc54** [comment]
Not sure what to say. The proc is started using `execve(cmd, arg, env)` which replaces the environment with the one specified (which includes all the envars we were given/collected), so...? Not much more I can do.

**Comment by Petter-Programs** [comment]
I just tested your most recent fix that you pushed, and it looks like it resolves the linker issue too when using fwd-environment (the LD_PRELOAD approach above still fails, but it doesn't really matter to me). Strange behavior, I guess the two issues must have been related, but I am happy just using fwd-environment.
