### ISSUE TITLE
Linking with libmpi.so in openmpi 1.8.3 generates a lot of warning using the intel compiler

### ISSUE THREAD

**Issue by bphusted** [open-mpi/ompi#251]
I have previously compiled my code with verison 1.6.5 of openmpi and the intel compiler 14 and using the -ipo (Interprocedural Optimization) option without any problems. If I do the same thing for the 1.8.3 version of openmpi a lot of warnings are generated.
ipo: warning #11021: unresolved opal_install_dirs
        Referenced in ....openmpi-1.8.3/lib/libmpi.so
The code links and also runs fine, but I am a bit puzzle by these warnings (more than 20) on unresolved references in libmpi.so

It seems that lib/libmpi.so ->  libmpi.so.1.6.0
So libmpi.so is the version belonging to openmpi 1.6 and not 1.8., or is the numbering of libmpi not related to the version of openmpi?

The initial installation was not done by me, so I to check if there was some error in the compilation I recompiled the complete openmpi with the intel compiler options. export CC=icc , export CXX=icpc , export F77=ifort export FC=ifort. 
I got the same results.

**Comment by marcocod** [comment]
Any news about this issue? I have the same problem of bphusted with the version latest 1.8.4.
I built the openmpi library with the intel compiler (15.0.2) and now during the linking I have a lot of ipo warning #11021. The only option in the configure I used is --prefix; the environment variables CC and CXX were icc and icpc; I didn't set any flags.
I tried also the versions 1.7.5 and 1.6.5: the 1.7.5 version is affected by this problem, the 1.6.5 seems ok.
If you need I can make more tests...

Here there's a part of the printed warnings:
![ipo_warnings](https://cloud.githubusercontent.com/assets/10694222/7379516/bfb63418-edf5-11e4-8fce-e04f8079858d.PNG)

**Comment by rhc54** [comment]
Should be fixed in the 1.8.5 about to be released - can you try the 1.8 nightly tarball to verify?

http://www.open-mpi.org/nightly/v1.8/

**Comment by marcocod** [comment]
ok, with the nightly version the problem is fixed.
So I'll wait the 1.8.5 version...

**Comment by jsquyres** [comment]
@marcocod Any news on trying a v1.8 nightly snapshot tarball?

**Comment by jsquyres** [comment]
@marcocod oops -- I didn't refresh my browser to see your prior response...

**Comment by marcocod** [comment]
Ok, I have some news.
When I compile my project, in the Makefile there are many (parallel) targets that share some objects. The list of ipo warnings appears only for some applications and not for the others.
I also tried to set as target only one of the application that shows the warnings but the issue remains.

**Comment by jsquyres** [comment]
@marcocod In re-reading this issue, let me answer a question that was previously unanswered: the numbering of libmpi.so.X is unrelated to the version number of Open MPI.  So libmpi.so.1.6 does not necessarily mean "Open MPI v1.6".

If you care: We use the GNU Libtool scheme for numbering our shared libraries: https://www.gnu.org/software/libtool/manual/libtool.html#Versioning

libmpi.so.1.6.0 actually corresponds to the v1.8.5 release.

**Comment by jsquyres** [comment]
This is very strange; I have more emails for this thread than are showing up here in the Github web UI...  Huh.

@marcocod One clarification: did you compile Open MPI with the Intel compiler, or gcc?  (I ask because you mention that you compiled your app with -ipo and not OMPI)

**Comment by jsquyres** [comment]
FWIW, I'm able to replicate this issue (build OMPI with Intel compiler, then build an MPI app with the Intel compiler and -ipo).  

I do note two things:

1. All of these messages are warnings; you still get a valid executable.
1. All the symbols it is complaining about are not in libmpi -- they are in other Open MPI libraries.

I think I know why you don't see these warnings in 1.6 and you do see them in 1.8.

In 1.6, the wrapper compiler explicitly lists all the Open MPI libraries on the underlying compiler command line: `-lmpi -lopen-rte -lopen-pal`.  In 1.8, we only list `-lmpi` and let the linker implicitly pull in the other two libraries.

Hence, I'm guessing that `-ipo` only using the libraries that are explicitly mentioned on the command line, not those implicitly pulled in by the linker.

I think you have two options:

1. You can work around this by adding `-lopen-rte -lopen-pal` on the command line.
1. You can ignore the warnings and just use the inlining from the MPI library.

**Comment by marcocod** [comment]
When I talked about version of openmpi I refered to the version of the package I downloaded.
To be more specific package 1.8.5 has the library libmpi.so.1.0.8 and package 1.6.5 has the library libmpi.so.1.6.0.
I compiled openmpi library with both gcc and intel compiler (I use the environment modules). If I use the intel compiler module I load the openmpi library built with intel compiler, if I use the gcc I use the openmpi library built with gcc.

**Comment by marcocod** [comment]
Thanks, now the reason of warnings is clear.
Anyway, in my opinion, it is better if the wrapper links explicitly all the libraries. Maybe you can add an option in the configure script for this.

**Comment by jsquyres** [comment]
We actually intentionally only link in -lmpi for long, complicated reasons.  See https://svn.open-mpi.org/trac/ompi/ticket/3422 if you care to see the sordid details.

That being said, there are workarounds if you want to link in the other libraries yourself (with the disclaimer that you'll break the reasons we do this).  E.g., --with-wrapper-libs, or setting an environment variable, or editing the mpi*wrapper-compiler-flags.txt files in $pkgdatadir.


> On Apr 30, 2015, at 6:05 PM, marcocod <notifications@github.com> wrote:
> 
> Thanks, now the reason of warnings is clear.
> Anyway, in my opinion, it is better if the wrapper links explicitly all the libraries. Maybe you can add an option in the configure script for this.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by bphusted** [comment]
@jsquyres Thanks for the clarification.
I just compiled openmpi 1.8.8 with the intel 16 compiler. The warnings also appears here during linking of my "own" program, but using -lopen-rte -lopen-pal on the command line made them disappear.
I think the issue can be closed.
