### ISSUE TITLE
Configure error

### ISSUE THREAD

**Issue by jennydaman** [open-mpi/ompi#2568]
I cannot compile openmpi, this is what I get in my configure log: 

```
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:6184: $? = 1
configure:6173: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
```

How can I work around this issue? I am on SolusOS, GCC v6.2.0

**Comment by ggouaillardet** [comment]
@jennydaman 
can you post the output of ```configure``` and ```config.log``` ?
at first glance, you are not looking at the right place in ```config.log```.
fwiw, a __lot__ of tests fail and this is normal, so you need to focus on the one (usually the last) that break ```configure```

**Comment by jennydaman** [comment]
After a few hours of looking around, I could ./configure after installing some more packages with 
`sudo eopkg install -c system.devel`
I've used ./configure, make, and make install, but still can't use mpirun..... None of the processes ended with an error though.

**Comment by jsquyres** [comment]
I'm afraid we can't tell much from your description.

Can you please supply all the information listed here: https://www.open-mpi.org/community/help/

**Comment by jennydaman** [comment]
Many apologies for wasting your time, but I fixed my own issue =/

Nothing was straightforward since I was trying to install openmpi on Solus, which does some things a bit differently. I didn't have a /usr/local folder. 
There was no discussion at all about openmpi on Solus. 
I fixed my problem by adding some lines to my .bashrc:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
export PATH=$PATH:/usr/local/bin
```

**Comment by jsquyres** [comment]
You can specify whatever directory you want for Open MPI to install to -- it's not Solaris specific.  For example:

```
$ ./configure --prefix=$HOME/my-openmpi-install
...
$ make install
```

This will configure, build, and install Open MPI into the `$HOME/my-openmpi-install` tree.  You can put whatever directory you want for the prefix; it just defaults to `/usr/local` if you don't supply it (regardless of your OS).

**Comment by cwilso6** [comment]
I am having the same issue. Below are the configure
[configure.txt](https://github.com/open-mpi/ompi/files/3536450/configure.txt)

 and configure.log
[config.log](https://github.com/open-mpi/ompi/files/3536445/config.log)

Please let me know if you need any additional information. Thank you in advance.

**Comment by dirtyharrycallahan** [comment]
Submitter wrote that he was using Solus OS not Solaris

**Comment by ggouaillardet** [comment]
@cwilso6 your gcc install seems busted as evidenced by the last error in `config.log`

```
configure:6377: checking whether we are cross compiling
configure:6385: gcc -o conftest    conftest.c  >&5
In file included from conftest.c:10:0:
/usr/local/lib/gcc/x86_64-apple-darwin17.5.0/7.3.0/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
 #include <_stdio.h>
          ^~~~~~~~~~
compilation terminated.
configure:6389: $? = 1
```

I suggest you troubleshoot this, and open a new issue the problem persists.
