### ISSUE TITLE
MPI spawn and "not enough slots" issue

### ISSUE THREAD

**Issue by iassiour** [open-mpi/ompi#6130]
Hi

I am getting "not enough slots" issues with MPI_Comm_Spawn in latest ompi 4.0.0. 
The issue can be reproduced if a slave is spawned on the host that the master runs.

I have set the oversubscribe option. (rmaps_base_oversubscribe = 1 in openmpi-mca-params.conf)

but this seems to be ignored for MPI_comm_spawn. 

Is there a way to specify oversubscribe for mpi spawn or disable the slots mechanism altogether.

Regards

**Comment by rhc54** [comment]
```ompi_info``` is your friend:
```shell
$ ompi_info --level 9 --param rmaps base
.
.
.
         MCA rmaps base: parameter "rmaps_base_inherit" (current value:
                          "false", data source: default, level: 9 dev/all,
                          type: bool)
                          Whether child jobs shall inherit launch directives
                          Valid values: 0: f|false|disabled|no|n, 1:
                          t|true|enabled|yes|y
```
So you need to add:
```
rmaps_base_inherit = 1
```
to your param file

**Comment by iassiour** [comment]
Hi,

I think that does not work. The following program would still complain about slots in the second call to MPI_comm_spaen even if I have added

rmaps_base_oversubscribe = 1
rmaps_base_inherit = 1

in the openmpi-mca-params.conf file

`  mpistat = MPI_Info_create(&minfo);
  mpistat = MPI_Info_set(minfo, "add-host", "host26");
  mpistat = MPI_Comm_spawn(slavejobtospawn, MPI_ARGV_NULL,
           1, minfo, 0, MPI_COMM_WORLD, &wcomm_, MPI_ERRCODES_IGNORE);

  int value = 500;

  mpistat = MPI_Send(&value, 1, MPI_INT, 0, 0, wcomm_);
  MPI_Status MPIerr;
  mpistat = MPI_Recv(&value, 1, MPI_INT, 0, 0, wcomm_, &MPIerr);

  mpistat = MPI_Info_create(&minfo2);
  mpistat = MPI_Info_set(minfo2, "add-host", "h26");
   mpistat = MPI_Comm_spawn(slavejobtospawn, MPI_ARGV_NULL,
           1, minfo2, 0, MPI_COMM_WORLD, &wcomm2_, MPI_ERRCODES_IGNORE);`

Thanks

**Comment by iassiour** [comment]
Hi,

I think that the slots issue is not limited to mpi spawn

The following complains about not enough slots 

$MPI_HOME/bin/mpirun  -H red9906025 -x LD_LIBRARY_PATH -np 1 mpi_master :  \
                                            -H red9906025,red9906028,red9906028,red9906028,red9906029,red9906029,red9906029,red9906029 -x LD_LIBRARY_PATH -np 8 mpi_master

I have  set rmaps_base_oversubscribe = 1 in openmpi-mca-params.conf

This used to work with 3.1.2. Is that flag now ignored?

**Comment by rhc54** [comment]
It is indeed a bug - fixed here: https://github.com/open-mpi/ompi/pull/6139

Thx for the report!

**Comment by iassiour** [comment]
Hi Ralph,

Thanks for the fix, Do you know if there is any other way to set the oversubscribe having to change the mpirun options with 4.0.0 

Also, is the rmaps_base_inherit flag still working as expected? (see my mpispawn example above)

**Comment by rhc54** [comment]
Oversubscribe is carried across regardless of inherit - it's one of the few things they decided to except from the inherit directive. It appears to be working for everything it is supposed to cover.

I'm afraid I don't know of any workaround for the problem

**Comment by iassiour** [comment]
In the mpi spawn case listed above I have set the -oversubscribe in mpirun but still get the 
"not enough slots" issue. 
So it looks to me oversubscribe is not carried to the spawn nodes. 
Would you mind having a look?

**Comment by abouteiller** [comment]
You may need to propagate https://github.com/open-mpi/ompi/pull/5968 to 4.x

**Comment by abouteiller** [comment]
Issue should be resolved in 4.0.1. Feel free to reopen if it persists.

**Comment by CrashLaker** [comment]
Facing the same issue with other versions of openmpi.
My problem:
```
--------------------------------------------------------------------------
All nodes which are allocated for this job are already filled.
--------------------------------------------------------------------------
```
I'm running with
```
rmaps_base_oversubscribe = 1
rmaps_base_inherit = 1
```
in `$prefix/etc/openmpi-mca-param.conf` of all nodes.

some hostfiles i've tested with:
```
controller max-slots=1
client     max-slots=3
gateway    max-slots=3
server1    max-slots=41
server2    max-slots=41
server3    max-slots=41
server4    max-slots=41
```
```
controller slots=1
client     slots=3
gateway    slots=3
server1    slots=41
server2    slots=41
server3    slots=41
server4    slots=41
```

versions:
- openhpc1.3.8
openmpi3/3.1.4 gnu8/8.3.0

- openmpi3.1.0 gnu8.3.0
- openmpi3.1.0 gnu4.8.0
- openmpi4.1.3 gnu8.3.0

openmpi4.1.3 got me this though https://github.com/open-mpi/ompi/issues/4555

**Comment by CrashLaker** [comment]
nvm. can confirm these versions are working.
it was actually a bug in my code

thank you
