### ISSUE TITLE
Wrong parsing of command line arguments with mpirun

### ISSUE THREAD

**Issue by angainor** [open-mpi/ompi#6372]
In 3.1.1 and 3.1.3 I get the following warning starting MPI applications that take the `--am` argument:

```
$ mpirun -H c11-3 ls --am aa bb
--------------------------------------------------------------------------
Process 130051 Unable to locate the variable file "aa" in the following search path:
   /cluster/software/OpenMPI/3.1.1-GCC-7.3.0-2.30/share/openmpi/amca-param-sets:/cluster/projects/nn9999k/
--------------------------------------------------------------------------
--------------------------------------------------------------------------
You're using the --am option. Please be advised that this option is deprecated;
you should use --tune instead. The --tune option allows one to specify mca
parameters as well as environment variables from within a file using the same
command line syntax (e.g. -mca var val -mca var "val" -x var=val -x var).
The --am option will be removed in a future release.
--------------------------------------------------------------------------
```

Of course `ls` doesn't take this argument, but that is only to illustrate the problem. It seems that `mpirun` is trying to analyze the application's arguments, and beyond the application name. Note that the above message is only displayed when the `-H` switch is present, and when there are at least 2 arguments after `--am`. Pretty funny, and only annoying: I do not see any other side effects except for the noise.

**Comment by jsquyres** [comment]
Hah, that's a fun bug!

Yes, it looks like something in the command line parsing is reading `--am` before it discards everything to the right (from OMPI's processing, anyway) of the command to be executed.  I simplified your example down to:

```
$ mpirun echo --am a b
```

A similar error happens on master HEAD, so this is likely behavior that has escaped attention for quite a while.

**Comment by SimonR1** [comment]
Dear everyone, 
I have the same problem and would be very grateful for any help or advice.

**Comment by awlauria** [comment]
I can take a look and see what's going on.

**Comment by rhc54** [comment]
FWIW: this is fixed in the RTE for OMPI v5. Problem is in not processing the cmd line before searching for mca params (including --am), thereby not knowing where the executable starts.

**Comment by awlauria** [comment]
Thanks @rhc54 .

@SimonR1 this will be fixed in the next major release.

**Comment by jsquyres** [comment]
I confirm: this is fixed on Open MPI master / what will eventually become v5.0.

I'm kinda guessing that this is not going to be fixed in prior releases, mainly due to lack of resources (i.e., no one has submitted a fix in 20+ months).

**Comment by loganharbour** [comment]
For those that have also scrambled across this like myself, it appears this is still not fully resolved:

```
[harblh@br006: ~ ]
$ mpiexec hostname
br006
br006
br010
br010
[harblh@br006: ~ ]
$ mpiexec hostname --help
mpiexec (Open MPI) 5.0.5

Usage: mpiexec [OPTION]...

See the mpirun(1) man page or HTML help for a detailed list of command
line options that are available.

Report bugs to https://www.open-mpi.org/community/help/
```

In the second case, `--help` is being passed as an argument to `mpiexec`

**Comment by rhc54** [comment]
It is (and has been for some time) fixed on the main branch, but there is a missing cherry-pick into the release branch. Have that in-process now.

**Comment by loganharbour** [comment]
> It is (and has been for some time) fixed on the main branch, but there is a missing cherry-pick into the release branch. Have that in-process now.

Great. Thanks for addressing this quickly!

**Comment by everythingfunctional** [comment]
I also just encountered this.

**Comment by loganharbour** [comment]
To be clear - the fix that @rhc54 was referencing did work for me. Just hasn't made it into a release.
