### ISSUE TITLE
mpirun has exited due to process rank 0 with PID 0 on node 

### ISSUE THREAD

**Issue by MostafaMAshry** [open-mpi/ompi#6379]
I try to use Open MPI-4.0.0 to run my FORTRAN code,
```
ashry@ashry-Precision-T1700:~$ which mpif90
/home/ashry/openmpi/bin/mpif90
ashry@ashry-Precision-T1700:~$ which mpirun
/home/ashry/openmpi/bin/mpirun
```
* Operating system/version: Ubuntu 18.10 

## Details of the problem

The error message is  as follows:
```
ashry@ashry-Precision-T1700:~/NGDPgeoid/src$ mpirun ./GGeoid
 process           1 of           4 is alive
 process           3 of           4 is alive
 process           2 of           4 is alive
 *************************
     Dealing with V1 !    
  Initialization is done! 
 Jtmp        4320
 *************************
 process           0 of           4 is alive
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.56245350599056110     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.56525362099637277     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.56554555500042625     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.56226904902723618     
--------------------------------------------------------------------------
mpirun has exited due to process rank 0 with PID 0 on
node ashry-Precision-T1700 exiting improperly. There are three reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).

You can avoid this message by specifying -quiet on the mpirun command line.
```

**Comment by jsquyres** [comment]
Did you read the error message?  It hypothesizes 3 threads why you would have seen that message.

**Comment by MostafaMAshry** [comment]
```
ashry@ashry-Precision-T1700:~/NGDPgeoid/src$ mpirun -np 4 --map-by node -machinefile myhosts GGeoid > test38.txt
ssh: Could not resolve hostname node4: Temporary failure in name resolution
ssh: Could not resolve hostname node1: Temporary failure in name resolution
ssh: Could not resolve hostname node2: Temporary failure in name resolution
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
ssh: Could not resolve hostname node3: Temporary failure in name resolution
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   ashry-Precision-T1700
  target node:  node1

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------
[ashry-Precision-T1700:18161] 2 more processes have sent help message help-errmgr-base.txt / no-path
[ashry-Precision-T1700:18161] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

**Comment by rhc54** [comment]
@MostafaMAshry The error messages (all of them, not just the ones coming out of OMPI itself) are telling you the problem.

> ssh: Could not resolve hostname node4: Temporary failure in name resolution
ssh: Could not resolve hostname node1: Temporary failure in name resolution
ssh: Could not resolve hostname node2: Temporary failure in name resolution
ssh: Could not resolve hostname node3: Temporary failure in name resolution

Your hostfile contains nodes that your system isn't recognizing - i.e., your Ethernet doesn't appear to have an IP address for node1, node2, node3, or node4. Given those names, I suspect you just made them up, yes?

**Comment by MostafaMAshry** [comment]
yes, I just create myhost file, I work in my own PC, and I don't know where I can add the nodes name in my system as when I open files hosts and hostname in /etc  I couldn't edit them (read only).

**Comment by MostafaMAshry** [comment]
yes,
here my hosts file after edit the nodes
```
127.0.0.1	localhost
127.0.1.1	ashry-Precision-T1700
127.0.1.2	node1
127.0.1.3	node2
127.0.1.4	node3
127.0.1.5	node4
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
and this is my host file:
```#data
#ashry-Precision-T1700
node1.mydomain.com
node2.mydomain.com
node3.mydomain.com
node4.mydomain.com
```
and the error still appear 
```
ashry@ashry-Precision-T1700:~/NGDPgeoid/src$ mpirun -np 4 --map-by node -machinefile myhosts GGeoid 
ssh: connect to host node2 port 22: Connection refused
ssh: connect to host node3 port 22: Connection refused
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   ashry-Precision-T1700
  target node:  node1

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------
[ashry-Precision-T1700:03382] 2 more processes have sent help message help-errmgr-base.txt / no-path
[ashry-Precision-T1700:03382] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
ssh: connect to host node4 port 22: Connection refused
ssh: connect to host node1 port 22: Connection refused
ashry@ashry-Precision-T1700:~/NGDPgeoid/src$ 
```

**Comment by jsquyres** [comment]
You should not be using 127.x.y.z for remote node IP addresses.  The entire 127.x.y.z range is reserved for localhost-only communications.  You should probably use 192.168.x.y (pick x and y values that are not used anywhere else on your network).

Just to be clear: Open MPI is telling you exactly what is going wrong.  You have posted two different errors on this issue, suggesting that you have changed something.  Initially, the error included lines like this:

```
ssh: Could not resolve hostname node4: Temporary failure in name resolution
ssh: Could not resolve hostname node1: Temporary failure in name resolution
ssh: Could not resolve hostname node2: Temporary failure in name resolution
```

This means that ssh was unable to resolve hostnames (e.g., `node4`) to an IP address.  If you now have complete `/etc/hosts` files on all your nodes, this problem may have been solved (although, as mentioned above, you really should not be using 127.x.y.z for remote IP addresses).

The 2nd message included lines like this:

```
ssh: connect to host node2 port 22: Connection refused
ssh: connect to host node3 port 22: Connection refused
```

which means that Open MPI can't ssh from one node to another.

You need to fix these networking issues before Open MPI can function properly:

1. Fix the IP addresses of all your nodes and update all `/etc/hosts` to match
1. Setup password-less `ssh` between all of your nodes.  From any node, you should be able to do this without entering passwords or passphrases:
```
ssh node1 hostname
ssh node2 hostname
ssh node3 hostname
ssh node4 hostname
```

**Comment by MostafaMAshry** [comment]
Thanks Prof. @jsquyres 
I fix the IP addresses of my four points and the first error disappear, But still I have problem in setup password-less, I try a lot of techniques and watch lots of videos in the internet, but the problem still appear,
Kindly, can you explain the steps of doing that, or recommended book that I can use to git rid of all this points.
Thanks in advance

**Comment by jsquyres** [comment]
I don't know if I'll be able to explain password-less ssh better than the internet tutorials out there.  😦 

My suggestion:
* Backup your `$HOME/.ssh` directory
* Delete your `$HOME/.ssh/` directory
* Now that you have a fresh/clean/empty ssh setup, start the password-less ssh setup again.
* If you don't have a common NFS `$HOME` directory between your machines, you will need to be exceedingly careful, precise, and methodical.  I suggest setting up ssh on one machine and then copying your `$HOME/.ssh` directory to each other machine (so that you are guaranteed that it is the same between all of them).
* For your first attempt, you might want to use empty passphrases (i.e., just hit enter when `ssh-keygen` asks for a passphrase).  After you understand the process more, you may consider adding a phassphrase to your ssh key.

**Comment by MostafaMAshry** [comment]
Thanks @jsquyres
Done, But with a new error O.o
```
process           2 of          16 is alive
 process           3 of          16 is alive
 process           4 of          16 is alive
 process           5 of          16 is alive
 process           6 of          16 is alive
 process           7 of          16 is alive
 process           8 of          16 is alive
 process           9 of          16 is alive
 process           1 of          16 is alive
 process          10 of          16 is alive
 process          11 of          16 is alive
 process          12 of          16 is alive
 process          13 of          16 is alive
 process          14 of          16 is alive
 process          15 of          16 is alive
 *************************
     Dealing with V1 !    
  Initialization is done! 
 Jtmp        4320
 *************************
 process           0 of          16 is alive
   3832.8351402837689     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31098980084061623     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31304744957014918     
   3832.8351402837689     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31425058003515005     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31427695183083415     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31391214067116380     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31283620884642005     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31450483622029424     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31457786401733756     
   0.0000000000000000     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31466646492481232     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31422459473833442     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31517322594299912     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31632850784808397     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31580681307241321     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31436136271804571     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31499144295230508     
   3832.8351402837689     
   0.0000000000000000     
   0.0000000000000000     
   0.0000000000000000     
 Elapsed time  0.31871095299720764     
```
I don't know what is the reason of this, 
## The above error comes when I write a script and use sbatch.
when I use mpirun I got this message:
![outmpirun](https://user-images.githubusercontent.com/47279494/52991395-8201f700-3447-11e9-8ec1-0b89b136bb5d.png)

**Comment by MostafaMAshry** [comment]
Thanks @jsquyres  Job is done
```
 *************************************
 Newton integral time (parallel)  0.41816749300000000     
    Parallel computation is done :)   
 *************************************
 	Job is done :) Bye! 
 *************************************
 I am HERE
```
