### ISSUE TITLE
PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206

### ISSUE THREAD

**Issue by letmaik** [open-mpi/ompi#7516]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
4.0.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
homebrew

### Please describe the system on which you are running

* Operating system/version: macOS 10.13.6
* Computer hardware: n/a (continuous integration system)
* Network type: n/a

-----------------------------

## Details of the problem

Error: 
> [Mac-802.local:41496] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206

The only variable I'm setting is:
```
export OMPI_MCA_btl=self,tcp
```

Previously this worked, so I'm assuming it's due to an Open MPI update pulled in via homebrew. The error happens when running part of the WRF weather model on a CI system (Azure Pipelines).

The line mentioned in the error corresponds to the following within the `pmix_ds12_lock_finalize` function:
```c
if (0 != pthread_rwlock_destroy(pthread_lock->rwlock)) {
  PMIX_ERROR_LOG(PMIX_ERROR);
```

Unfortunately I won't be able to provide a minimal example. Maybe the above still gives some clues on what might be going wrong.

**Comment by letmaik** [comment]
I just tried settting `PMIX_MCA_gds=^ds21` as suggested in https://github.com/openpmix/openpmix/issues/1114 and this seems to avoid the issue.

**Comment by rhc54** [comment]
Sadly, there is no way to diagnose this problem without the conf.log from the opal/mca/pmix/pmix3x directory. Have you tried building OMPI yourself to see if the problem persists?

**Comment by letmaik** [comment]
No, I'm simply a consumer of OMPI via homebrew. Why can't OMPI dump conf.log to the console if bad things happen?

**Comment by rhc54** [comment]
Because "config.log" isn't generated unless you run `configure` on that machine 😄 In this case, the homebrew maintainer did it on their machine and we have no record of it and no way of knowing what they did. Without that info, there really isn't anything we can do.

I can say that many of us in the developer community use Mac's and don't see this problem. However, we build it ourselves on our local machine. Best guess is that the homebrew maintainer has some configuration different from your own and thus the configure logic isn't reaching a result consistent with your system.

**Comment by letmaik** [comment]
I looked at the wrong log... `PMIX_MCA_gds=^ds21` didn't actually help, but `PMIX_MCA_gds=hash` seems to work.

**Comment by jsquyres** [comment]
FWIW, I'm able to replicate the issue with Open MPI v4.0.3 in Homebrew as of 2020-03-09 (today):

```
$ mpirun -np 2 hello_c
Hello, world, I am 0 of 2, (Open MPI v4.0.3, package: Open MPI brew@Catalina Distribution, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020, 108)
Hello, world, I am 1 of 2, (Open MPI v4.0.3, package: Open MPI brew@Catalina Distribution, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020, 108)
[JSQUYRES-M-26UT:83096] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206
[JSQUYRES-M-26UT:83095] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206
```

I'm also able to replicate this with a regular Open MPI v4.0.3 tarball, configured the same way as Homebrew (with my own `prefix`, of course):

```
./configure --with-hwloc=internal --prefix=/Users/jsquyres/bogus --enable-ipv6 --with-libevent=/usr/local/opt/libevent
```

Oddly, this isn't happening when I compile Open MPI at the head of the `v4.0.x` branch -- even with a VPATH build, which should effectively be the same as a tarball build.

**Comment by jsquyres** [comment]
FWIW, I don't know _why_, but with a little testing, I see the following:

* In both the 4.0.3 tarball and v4.0.x HEAD builds, ds21 is being chosen as the gds component (with priority 30).  So far, so good.
* In both the 4.0.3 tarball and v4.0.x HEAD builds, `ds12_finalize()` is invoked at the end of the MPI application -- assumedly to clean up the non-selected ds12 component.  `ds12_finalize()` invokes `pmix_common_dstor_finalize(ds12_ctx)`.  So far, so good.
* In the 4.0.3 tarball, `pmix_common_dstor_finalize()` invokes `pmix_ds12_lock_finalize()`.
    * For `mpirun -np 2 ring_c`, this happens three times (assumedly in `orterun` and in the 2 instances of `hello_c`).
    * The first time, it completes without error.
    * The second two times, we see the PMIX ERROR messages.
* In the v4.0.x HEAD builds, `pmix_common_dstor_finalize()` DOES NOT invoke `pmix_ds12_lock_finalize()`.

I'm not sure why there's a disparity in the behavior between these two...?

**Comment by NKcqx** [comment]
I encoutered the same problem, using version 4.0.3 and build by myself on Mac.

**Comment by rhc54** [comment]
FWIW: the error report is harmless, albeit annoying, noise. You can shut it off with:
```text
PMIX_MCA_gds=^ds12
```
Note the `ds12` - _not_ `ds21` as was previously reported.

**Comment by artpol84** [comment]
@karasevb please have a look.

**Comment by rhc54** [comment]
FWIW: I already fixed this in PMIx. Just didn't close this issue because it hasn't come over into OMPI v4 yet.

**Comment by karasevb** [comment]
@rhc54 could you please add a reference to the fix?

**Comment by rhc54** [comment]
PMIx master: https://github.com/openpmix/openpmix/pull/1668
PMIx v3.1: https://github.com/openpmix/openpmix/pull/1669

Note that we will be releasing a PMIx v3.1.6 in the near future and updating OMPI v4.0.x with it.

**Comment by artpol84** [comment]
@rhc54 the fix looks like masking the issue. Are we sure that there is no real problem and we can just silence it?

@karasevb if ds12 is not selected, will it allocate it's resources anyway? My guess is yes, but I'm not sure.
If the above is correct, why it barfs at the finalize? Can it be that double-free is happening?

**Comment by WeiJieQiang** [comment]
I have the same problem with homebrew installed open-mpi 4.0.3 in maxOS. `PMIX_MCA_gds=hash` seems to work.

**Comment by Geokeke** [comment]
I encoutered the same problem, using version 4.0.3 and build by myself on Mac.

**Comment by farzado** [comment]
Experienced the same issue after installing via Homebrew. `export PMIX_MCA_gds=hash` worked for me.

**Comment by rhc54** [comment]
Please, folks - you don't all have to keep telling us about this. As noted above, it has been fixed in the OMPI v4.0.x branch and will appear in a future release. For now, just export the `PMIX_MCA_gds=hash` envar.

**Comment by leofang** [comment]
@rhc54, @dalcinl and I are seeing this issue when building Open MPI v4.0.3 for conda-forge (see https://github.com/conda-forge/openmpi-feedstock/pull/57#issuecomment-610678486). Just wanna make sure this is expected not fixed yet in v4.0.3, right?

**Comment by rhc54** [comment]
Correct - there is another bug in 4.0.3 that might necessitate an update of PMIx in that branch. We are waiting on an assessment of that situation before committing an OMPI-specific patch.

**Comment by leofang** [comment]
Thanks for confirming, Ralph!

**Comment by lcebaman** [comment]
OpenMPI 4.0.3  on Mac OS X Catalina gives

```
mpirun -n 2 ./hello
[MBP15-LC.local:36606] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206
[MBP15-LC.local:36609] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 206
```
but it is fixed with
```
MBP15-LC:$ export PMIX_MCA_gds=hash
MBP15-LC:$ mpirun -n 2 ./hello
```
I am not sure if the error is harmless though

**Comment by jsquyres** [comment]
This was fixed in Open MPI v4.0.4.  Closing.

**Comment by pogevip** [comment]
> 我查看了错误的日志...`PMIX_MCA_gds=^ds21`实际上并没有帮助，但`PMIX_MCA_gds=hash`似乎可以正常工作。

It works for me.
