### ISSUE TITLE
cobuild doesn't work

### ISSUE THREAD

**Issue by abouteiller** [open-mpi/ompi#9625]
## Background information

Some cobuild' infrastructure that was modified in Open PMIx and PRRTE isn't compatible with Open MPI configure structure. That means that using PMIx/PRRTE master is not currently possible (external builds will work fine). 

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

```
git show
7d1711fd (HEAD -> master, origin/master, origin/HEAD) Merge pull request #9616 from jjhursey/libnbc-fix-overflow         Josh Hursey 25 hours ago
```

```
git submodule
+2cbdee234bd9fb5b3aa5ef3f626c9139b8416000 3rd-party/openpmix (v1.1.3-3250-g2cbdee23)
+1b6162fb75c432b7bb37f0702192df60e73c9e2a 3rd-party/prrte (psrvr-v2.0.0rc1-4080-g1b6162fb)
```

### Please describe the system on which you are running

* Operating system/version: CentOS/7 gcc/7.3
* Computer hardware: x86_64
* Network type: N/A

-----------------------------

## Details of the problem

```
../master/configure --prefix=/home/bouteill/ompi/master.debug --enable-prte-prefix-by-default --enable-debug --enable-picky --enable-mpi-java --without-ucx --with-hwloc=internal --with-pmix=internal --with-libevent=internal
```

Using the 'internal' flags will cause the following configure to be passed to OpenPMIx

```
../../../master/3rd-party/openpmix/configure --disable-option-checking --prefix=/home/bouteill/ompi/master.debug --without-tests-examples --disable-pmix-binaries --disable-pmix-backward-compatibility --disable-visibility --with-libevent=cobuild --with-hwloc=cobuild '--with-prte-extra-lib= /home/bouteill/ompi/master.debug/3rd-party/libevent-2.1.12-stable/libevent_core.la /home/bouteill/ompi/master.debug/3rd-party/libevent-2.1.12-stable/libevent_pthreads.la /home/bouteill/ompi/master.debug/3rd-party/hwloc-2.4.0/hwloc/libhwloc.la' --enable-debug --enable-prte-prefix-by-default --enable-debug --enable-picky --enable-mpi-java --without-ucx CC=/sw/spack/2021-02-12/opt/spack/linux-scientific7-x86_64/gcc-7.3.0/gcc-7.3.0-w4y27e3bu2ubqf6xfx7a2qdnuuwl5je7/bin/gcc 'CPPFLAGS= -I/home/bouteill/ompi/master.debug/3rd-party/libevent-2.1.12-stable -I/home/bouteill/ompi/master.debug/3rd-party/libevent-2.1.12-stable/include -I/home/bouteill/ompi/master.debug/3rd-party/hwloc-2.4.0/include -I/home/bouteill/ompi/master/3rd-party/hwloc-2.4.0/include'  --cache-file=/dev/null --srcdir=../../../master/3rd-party/openpmix
```

Note how CPPFLAGS is incorrectly space-mangled with 'gcc', and how '--with-pret-extra-lib=' starts with a space.

The resulting configure runs with the following errors and defects:
```

============================================================================
== Event libraries
============================================================================
checking --with-libev value... simple ok (unspecified)
checking --with-libev-libdir value... simple ok (unspecified)
checking will libev support be built... no
configure: looking for header in cobuild
checking for event.h... yes
configure: looking for library without search path
checking for library containing event_config_new... -levent_core
checking for evthread_set_lock_callbacks in -levent_core... yes
checking for evthread_use_pthreads in -levent_pthreads... yes
checking if libevent version is 2.0.21 or greater... yes
checking will libevent support be built... yes

============================================================================
== HWLOC
============================================================================
configure: looking for header in cobuild
checking for hwloc.h... yes
configure: WARNING: Could not find cobuild/lib or cobuild/lib64
configure: error: Can not continue
configure: ===== done with 3rd-party/openpmix configure =====
configure: error: Could not find viable pmix build.
```

Both of these entries are incorrect:
1. 'looking for headers in 'cobuild' is from `configure:31186: checking for event.h
configure:31186: gcc -c -g -finline-functions -pthread  -I/home/bouteill/ompi/master.debug/3rd-party/libevent-2.1.12-stable -I/home/bouteill/ompi/master.debug/3rd-party/libevent-2.1.12-stable/include -I/home/bouteill/ompi/master.debug/3rd-party/hwloc-2.4.0/include -I/home/bouteill/ompi/master/3rd-party/hwloc-2.4.0/include  -Icobuild conftest.c >&5`, the -Icobuild is wrong (but that doesn't break)
2. Missing the -L3rd-party/libevent-2.1.12-stable/lib: 
```configure:31557: gcc -o conftest -g -finline-functions -pthread  -I/home/boute
ill/ompi/master.debug/3rd-party/libevent-2.1.12-stable -I/home/bouteill/ompi/master.debug/3rd-party/libevent-2.1.12-stable/include -I/home/bouteill/ompi/master.debug/3rd-party/hwloc-2.4.0/inc
lude -I/home/bouteill/ompi/master/3rd-party/hwloc-2.4.0/include  -Icobuild   conftest.c -levent_core -levent_pthreads -lm -lutil   >&5
configure:31557: $? = 0
configure:31577: result: -levent_core
configure:32122: checking for evthread_set_lock_callbacks in -levent_core
configure:32145: gcc -o conftest -g -finline-functions -pthread  -I/home/bouteill/ompi/master.debug/3rd-party/libevent-2.1.12-stable -I/home/bouteill/ompi/master.debug/3rd-party/libevent-2.1.12-stable/include -I/home/bouteill/ompi/master.debug/3rd-party/hwloc-2.4.0/include -I/home/bouteill/ompi/master/3rd-party/hwloc-2.4.0/include  -Icobuild   conftest.c -levent_core  -levent_core -lm -lutil   -levent_pthreads >&5
```
This is linking the system installed libevent (rather than the 3rd-party provided one from the 'cobuild', resulting in a number of runtime defects because the .h and the .so are not matching. 
3. Adding -Lcobuild to hwloc

**Comment by ggouaillardet** [comment]
@abouteiller are you sure your submodules are up-to-date?

Here is what you have in the embedded Open PMIx
```
============================================================================
== Event libraries
============================================================================
checking --with-libev value... simple ok (unspecified)
checking --with-libev-libdir value... simple ok (unspecified)
checking will libev support be built... no
configure: looking for header in cobuild
```
(`cobuild` is treated as a directory)
but here is what I have
```
============================================================================
== Event libraries
============================================================================
checking --with-libev value... simple ok (unspecified)
checking --with-libev-libdir value... simple ok (unspecified)
checking will libev support be built... no
checking for libevent... cobuild
checking if co-built libevent includes thread support... yes
```
(here `cobuild` has a special meaning)

yes, there are two unnecessary whitespace (`--with-prte-extra-libs= /...` and `CPPFLAGS= -I/...` but since these are correctly quoted, they should have zero impact on the outcome.

**Comment by rhc54** [comment]
The problem is that @abouteiller must have done a `git pull` on the master branches of the PMIx and PRRTE repos. As was reported to the RMs and is scheduled to be discussed in an upcoming Tues meeting, we have diverged on the configure logic. Long explanation, but basically OMPI can no longer use the master branches of those repos.

I'm afraid you'll need to revert both of the submodules to the hash of their last OMPI commit.

**Comment by rhc54** [comment]
Sorry - should have take a little extra time to be clear. It is only the configure logic that has diverged. Thus, you cannot move the submodule pointers in OMPI master.

However, you _can_ clone the PMIx/PRRTE repos and build/use them externally. They are functionally just fine.

**Comment by abouteiller** [comment]
Thanks, that was indeed the issue. I changed the labels to reflect current status (i.e., waiting on reconciliation) but left open so that somebody experiencing the same problem finds it.

**Comment by mwheinz** [comment]
Is anyone working on this? This is blocking #9658 - the bug is fixed in Open PMIX but we can't update the submodule pointer to a version which contains the fix.

**Comment by gpaulsen** [comment]
@abouteiller We've recently the configure changes to build PMIx and PRRTE release branches internally on v5.0.x.  Could you please retest?

**Comment by abouteiller** [comment]
@gpaulsen I tried with v5.0.x, I found the following issue: 

Open PMIX: 
1. 'configure' reports it is using `/usr/include` for finding internal components (e.g., lib event, hwloc, etc); this is a harmless inconsistency in the output log, Open PMIX is indeed compiled with `-I$VPATH/3rd-party/hwloc-2.4.0/include`
```
configure:32222: looking for header in /usr/include
configure:32226: checking for event.h
configure:32226: /sw/spack/2021-02-12/opt/spack/linux-scientific7-x86_64/gcc-7.3.0/gcc-7.3.0-w4y27e3bu2ubqf6xfx7a2qdnuuwl5je7/bin/gcc -c -O3 -DNDEBUG -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment
 -Wshadow -Werror-implicit-function-declaration -fno-strict-aliasing -pedantic -Wall -finline-functions -pthread  -I/home/bouteill/ompi/v5.0.x/build/3rd-party/libevent-2.1.12-stable -I/home/bouteill/ompi/v5.0.x/build/3rd-party/libevent-2.
1.12-stable/include -I/home/bouteill/ompi/v5.0.x/build/3rd-party/hwloc-2.4.0/include -I/home/bouteill/ompi/v5.0.x/3rd-party/hwloc-2.4.0/include  -I/usr/include conftest.c >&5
configure:32226: $? = 0
configure:32226: result: yes
```

2. make fails because it is missing `-L$VPATH/3rd-party/hwloc-2.4.0/lib`. This may be a canary that tells us that we are linking with system libevent/libpmix as well (if system installed) but the system version are just compatible so the error is silent. 
```
make[2]: Entering directory `/home/bouteill/ompi/v5.0.x/build/3rd-party/openpmix/src/tools/pevent'
/bin/sh ../../../libtool  --tag=CC   --mode=link /sw/spack/2021-02-12/opt/spack/linux-scientific7-x86_64/gcc-7.3.0/gcc-7.3.0-w4y27e3bu2ubqf6xfx7a2qdnuuwl5je7/bin/gcc -DPMIX_CONFIGURE_USER="\"bouteill\"" -DPMIX_CONFIGURE_HOST="\"saturn.icl.utk.edu\"" -DPMIX_CONFIGURE_DATE="\"Fri Jan 14 17:32:01 UTC 2022\"" -DPMIX_BUILD_USER="\"$USER\"" -DPMIX_BUILD_HOST="\"${HOSTNAME:-`(hostname || uname -n) | sed 1q`}\"" -DPMIX_BUILD_DATE="\"`../../../../../../3rd-party/openpmix/config/getdate.sh`\"" -DPMIX_BUILD_CFLAGS="\"-O3 -DNDEBUG -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -Wshadow -Werror-implicit-function-declaration -fno-strict-aliasing -pedantic -Wall -finline-functions -pthread\"" -DPMIX_BUILD_CPPFLAGS="\"-iquote/home/bouteill/ompi/v5.0.x/build/3rd-party/openpmix -iquote/home/bouteill/ompi/v5.0.x/3rd-party/openpmix -iquote/home/bouteill/ompi/v5.0.x/3rd-party/openpmix/src -iquote/home/bouteill/ompi/v5.0.x/build/3rd-party/openpmix/include -I/home/bouteill/ompi/v5.0.x/3rd-party/openpmix/include -I/home/bouteill/ompi/v5.0.x/build/3rd-party/libevent-2.1.12-stable -I/home/bouteill/ompi/v5.0.x/build/3rd-party/libevent-2.1.12-stable/include -I/home/bouteill/ompi/v5.0.x/build/3rd-party/hwloc-2.4.0/include -I/home/bouteill/ompi/v5.0.x/3rd-party/hwloc-2.4.0/include\"" -DPMIX_BUILD_LDFLAGS="\"\"" -DPMIX_BUILD_LIBS="\"-lm -lutil -ldl -levent_core -levent_pthreads -lhwloc\"" -DPMIX_CC_ABSOLUTE="\"\"" -DPMIX_GREEK_VERSION="\"rc2\"" -DPMIX_REPO_REV="\"v4.1.1rc2\"" -DPMIX_RELEASE_DATE="\"Unreleased developer copy\"" -O3 -DNDEBUG -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -Wshadow -Werror-implicit-function-declaration -fno-strict-aliasing -pedantic -Wall -finline-functions -pthread   -o pevent pevent.o  ../../../src/libpmix.la -lm -lutil -ldl -levent_core -levent_pthreads -lhwloc
libtool: link: /sw/spack/2021-02-12/opt/spack/linux-scientific7-x86_64/gcc-7.3.0/gcc-7.3.0-w4y27e3bu2ubqf6xfx7a2qdnuuwl5je7/bin/gcc -DPMIX_CONFIGURE_USER=\"bouteill\" -DPMIX_CONFIGURE_HOST=\"saturn.icl.utk.edu\" "-DPMIX_CONFIGURE_DATE=\"Fri Jan 14 17:32:01 UTC 2022\"" -DPMIX_BUILD_USER=\"bouteill\" -DPMIX_BUILD_HOST=\"saturn.icl.utk.edu\" "-DPMIX_BUILD_DATE=\"Fri Jan 14 17:46:19 UTC 2022\"" "-DPMIX_BUILD_CFLAGS=\"-O3 -DNDEBUG -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -Wshadow -Werror-implicit-function-declaration -fno-strict-aliasing -pedantic -Wall -finline-functions -pthread\"" "-DPMIX_BUILD_CPPFLAGS=\"-iquote/home/bouteill/ompi/v5.0.x/build/3rd-party/openpmix -iquote/home/bouteill/ompi/v5.0.x/3rd-party/openpmix -iquote/home/bouteill/ompi/v5.0.x/3rd-party/openpmix/src -iquote/home/bouteill/ompi/v5.0.x/build/3rd-party/openpmix/include -I/home/bouteill/ompi/v5.0.x/3rd-party/openpmix/include -I/home/bouteill/ompi/v5.0.x/build/3rd-party/libevent-2.1.12-stable -I/home/bouteill/ompi/v5.0.x/build/3rd-party/libevent-2.1.12-stable/include -I/home/bouteill/ompi/v5.0.x/build/3rd-party/hwloc-2.4.0/include -I/home/bouteill/ompi/v5.0.x/3rd-party/hwloc-2.4.0/include\"" -DPMIX_BUILD_LDFLAGS=\"\" "-DPMIX_BUILD_LIBS=\"-lm -lutil -ldl -levent_core -levent_pthreads -lhwloc\"" -DPMIX_CC_ABSOLUTE=\"\" -DPMIX_GREEK_VERSION=\"rc2\" -DPMIX_REPO_REV=\"v4.1.1rc2\" "-DPMIX_RELEASE_DATE=\"Unreleased developer copy\"" -O3 -DNDEBUG -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -Wshadow -Werror-implicit-function-declaration -fno-strict-aliasing -pedantic -Wall -finline-functions -pthread -o .libs/pevent pevent.o  ../../../src/.libs/libpmix.so -lm -lutil -ldl -levent_core -levent_pthreads -lhwloc -pthread -Wl,-rpath -Wl,/home/bouteill/ompi/v5.0.x/build/lib
../../../src/.libs/libpmix.so: undefined reference to `hwloc_shmem_topology_write'
../../../src/.libs/libpmix.so: undefined reference to `hwloc_shmem_topology_adopt'
../../../src/.libs/libpmix.so: undefined reference to `hwloc_shmem_topology_get_length'
../../../src/.libs/libpmix.so: undefined reference to `hwloc_topology_set_io_types_filter'
collect2: error: ld returned 1 exit status
make[2]: *** [pevent] Error 1
```

Open PRTE: 'configure' fails
```
configure:29138: checking if libevent version is 2.0.21 or greater
configure:29157: /sw/spack/2021-02-12/opt/spack/linux-scientific7-x86_64/gcc-7.3.0/gcc-7.3.0-w4y27e3bu2ubqf6xfx7a2qdnuuwl5je7/bin/gcc -c -O3 -DNDEBUG -finline-functions -pthread  -I/home/bouteill/ompi/v5.0.x/build/3rd-party/libevent-2.1.12-stable -I/home/bouteill/ompi/v5.0.x/build/3rd-party/libevent-2.1.12-stable/include -I/home/bouteill/ompi/v5.0.x/build/3rd-party/hwloc-2.4.0/include -I/home/bouteill/ompi/v5.0.x/3rd-party/hwloc-2.4.0/include -I/home/bouteill/ompi/v5.0.x/build/3rd-party/openpmix/include -I/home/bouteill/ompi/v5.0.x/3rd-party/openpmix/include conftest.c >&5
configure:29157: $? = 0
configure:29159: result: yes
configure:29174: checking will libevent support be built
configure:29177: result: yes
configure:4003: === Configure PMIx
configure:29947: checking --with-pmix value
configure:29964: result: not found
configure:29966: WARNING: Expected file /usr/include/pmix.h not found
configure:29968: error: Cannot continue
```

Line above error shows that the `$VPATH/3rd-party/openpmix/include` is present so the test should have worked.

**Comment by abouteiller** [comment]
Maybe I misunderstood what you wanted me to test? 
👍 master WORKS
👎 v5.0.x still doesn't work (see above)

**Comment by gpaulsen** [comment]
Thanks @abouteiller v5 RMs will do an analysis of master vs v5.0.x and see what's missing.

**Comment by awlauria** [comment]
I cloned v5.0.x and cannot reproduce. My thinking it was resolved by this: https://github.com/open-mpi/ompi/pull/9873

@abouteiller can you re-clone and re-test?

**Comment by abouteiller** [comment]
All is good on 9314a427 @awlauria

**Comment by awlauria** [comment]
Thanks! 
closing.
